build:
  image: debian:latest
  commands:
    - apt-get update
    - apt-get install build-essential git cmake python
    - ./submodules/cmake-builder/prepare.py flexisip -DENABLE_SOCI=YES

clone:
  depth: 50
  recursive: true