build:
  image: gui13/flexisip-build-image
  commands:
    - ./submodules/cmake-builder/prepare.py flexisip-rpm -DENABLE_BC_ODBC=YES -DENABLE_SOCI=YES -DENABLE_SOCI_BUILD=YES
    - make -C WORK/flexisip-rpm/cmake

clone:
  depth: 50
  recursive: true

cache:
  mount:
    - .git